# Generated by Django 4.2.9 on 2024-09-13 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pet',
            name='size',
            field=models.CharField(choices=[('Toy', 'Toy'), ('Small', 'Small'), ('Medium', 'Medium'), ('Large', 'Large'), ('Giant', 'Giant')], default='Medium', max_length=10),
        ),
    ]
